### PR TITLE
Fentry - Update about-us.txt

### PR DESCRIPTION
**Pull request by fentrymartin7**

### CODE REVIEW

**Review by cunananan — APPROVED** [review]
Noice.

**Review by Aplas99 — APPROVED** [review]
looks good

**Review by Aigis421 — APPROVED** [review]
10/10

**Review by Aigis421 — COMMENTED** [review]
10/10

**Review by axpazmino — CHANGES_REQUESTED** [review]
Miguel is listed twice and kevin is listed twice

**Pull request merged**
